<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <Description>Among Us Salem</Description>
        <RootNamespace>AmongUsSalem</RootNamespace>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\**\*.*"/>
    </ItemGroup>

    <Import Project="../AmongUs.props"/>

</Project>