namespace TownOfUs.Modules.Localization;

public enum TouNames
{
    // Crewmate Roles
    Altruist,
    Aurial,
    Cleric,
    Deputy,
    Detective,
    Engineer,
    Haunter,
    Hunter,
    Imitator,
    Investigator,
    Jailor,
    Lookout,
    Mayor,
    Medic,
    Medium,
    Mirrorcaster,
    Mystic,
    Oracle,
    Plumber,
    Politician,
    Prosecutor,
    Seer,
    Sheriff,
    Snitch,
    Spy,
    Swapper,
    Tracker,
    Transporter,
    Trapper,
    Veteran,
    Vigilante,
    Warden,
    // Impostor Roles
    Ambassador,
    Ambusher,
    Blackmailer,
    Bomber,
    Eclipsal,
    Escapist,
    Grenadier,
    Herbalist,
    Hypnotist,
    Infestor,
    Janitor,
    Miner,
    Morphling,
    Scavenger,
    Swooper,
    Traitor,
    Undertaker,
    Venerer,
    Warlock,
    // Neutral Roles
    Amnesiac,
    Arsonist,
    Doomsayer,
    Executioner,
    Glitch,
    GuardianAngel,
    Inquisitor,
    Jester,
    Juggernaut,
    Mercenary,
    Pestilence,
    Phantom,
    Plaguebearer,
    SoulCollector,
    Survivor,
    Vampire,
    Werewolf,
    // Alliance Modifiers
    Egotist,
    Lover,
    Lovers, // for plural
    // Universal Modifiers
    ButtonBarry,
    Flash,
    Giant,
    Immovable,
    Mini,
    Radar,
    Satellite,
    Shy,
    SixthSense,
    Sleuth,
    Tiebreaker,
    // Impostor Modifiers
    Disperser,
    Saboteur,
    Telepath,
    Underdog,
    // Assailant Modifiers (NK/Imp)
    Assassin,
    DoubleShot,
    // Crewmate Modifiers
    Aftermath,
    Bait,
    Celebrity,
    Diseased,
    Frosty,
    Multitasker,
    Noisemaker,
    Operative,
    Rotting,
    Scientist,
    Scout,
    Taskmaster,
    Torch,
    // Other Modifiers
    FirstDeathShield,
    Scatter,
    // EVERYTHING BELOW HERE IS FOR THE SIDEMEN, THEY ARE NOT FOR PUBLIC RELEASE!
    Astral,
    PuppetMaster,
    Mage,
    Sandworm,
    Rcxd,
    Poisoner,
    Sniper,
    Cannibal,
    Timelord
}